# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'sectionskQFsGA.ui'
##
## Created by: Qt User Interface Compiler version 6.2.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from qt_core import *

from PyQt5 import QtGui

class Ui_Secoes(object):
    def setupUi(self, Secoes):
        if not Secoes.objectName():
            Secoes.setObjectName(u"Secoes")
        Secoes.resize(350, 760)
        Secoes.setStyleSheet(u"#general{background-color: rgb(23, 23, 23);}\n"
"#linear_parts{background-color: rgb(23, 23, 23);}\n"
"#esteganography{background-color: rgb(23, 23, 23);}\n"
"#filters{background-color: rgb(23, 23, 23);}")
        self.linear_parts = QWidget()
        self.linear_parts.setObjectName(u"linear_parts")
        self.points_x_values = QPlainTextEdit(self.linear_parts)
        self.points_x_values.setObjectName(u"points_x_values")
        self.points_x_values.setGeometry(QRect(40, 120, 271, 31))
        self.points_x_values.setStyleSheet(u"font: 10pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(23, 23, 23);")
        self.points_y_label = QLabel(self.linear_parts)
        self.points_y_label.setObjectName(u"points_y_label")
        self.points_y_label.setGeometry(QRect(150, 160, 51, 31))
        self.lp_title = QLabel(self.linear_parts)
        self.lp_title.setObjectName(u"lp_title")
        self.lp_title.setGeometry(QRect(20, 20, 171, 31))
        self.lp_title.setLayoutDirection(Qt.LeftToRight)
        self.lp_title.setAlignment(Qt.AlignCenter)
        self.points_x_label = QLabel(self.linear_parts)
        self.points_x_label.setObjectName(u"points_x_label")
        self.points_x_label.setGeometry(QRect(150, 90, 51, 31))
        self.points_y_values = QPlainTextEdit(self.linear_parts)
        self.points_y_values.setObjectName(u"points_y_values")
        self.points_y_values.setGeometry(QRect(40, 190, 271, 31))
        self.points_y_values.setStyleSheet(u"font: 10pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(23, 23, 23);")
        self.see_plot_button = QPushButton(self.linear_parts)
        self.see_plot_button.setObjectName(u"see_plot_button")
        self.see_plot_button.setGeometry(QRect(110, 250, 131, 31))
        self.see_plot_button.setStyleSheet(u"background-color: rgb(23, 23, 23);\n"
"color: rgb(255, 255, 255);")
        self.lp_bool = QCheckBox(self.linear_parts)
        self.lp_bool.setObjectName(u"lp_bool")
        self.lp_bool.setGeometry(QRect(100, 310, 151, 41))
        self.lp_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.lp_image = QLabel(self.linear_parts)
        self.lp_image.setObjectName(u"lp_image")
        self.lp_image.setGeometry(QRect(10, 410, 321, 201))
        self.lp_image.setMinimumSize(QSize(321, 201))
        Secoes.addWidget(self.linear_parts)
        self.esteganography = QWidget()
        self.esteganography.setObjectName(u"esteganography")
        self.already_label = QLabel(self.esteganography)
        self.already_label.setObjectName(u"already_label")
        self.already_label.setGeometry(QRect(80, 320, 201, 31))
        self.esteg_title = QLabel(self.esteganography)
        self.esteg_title.setObjectName(u"esteg_title")
        self.esteg_title.setGeometry(QRect(20, 20, 181, 31))
        self.encode_button = QPushButton(self.esteganography)
        self.encode_button.setObjectName(u"encode_button")
        self.encode_button.setGeometry(QRect(100, 220, 151, 31))
        self.encode_button.setStyleSheet(u"background-color: rgb(82, 82, 82);\n"
"color: rgb(255, 255, 255);")
        self.esteg_entry_text = QPlainTextEdit(self.esteganography)
        self.esteg_entry_text.setObjectName(u"esteg_entry_text")
        self.esteg_entry_text.setGeometry(QRect(30, 70, 281, 131))
        self.esteg_entry_text.setStyleSheet(u"font: 10pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(23, 23, 23);")
        self.decode_button = QPushButton(self.esteganography)
        self.decode_button.setObjectName(u"decode_button")
        self.decode_button.setGeometry(QRect(100, 350, 151, 31))
        self.decode_button.setAutoFillBackground(False)
        self.decode_button.setStyleSheet(u"background-color: rgb(82, 82, 82);\n"
"color: rgb(255, 255, 255);")
        self.decrypted_label = QLabel(self.esteganography)
        self.decrypted_label.setObjectName(u"decrypted_label")
        self.decrypted_label.setGeometry(QRect(50, 420, 251, 141))
        self.decrypted_label.setStyleSheet(u"font: 700 14pt \"Segoe UI\";")
        Secoes.addWidget(self.esteganography)
        self.general = QWidget()
        self.general.setObjectName(u"general")
        self.equalize_bool = QCheckBox(self.general)
        self.equalize_bool.setObjectName(u"equalize_bool")
        self.equalize_bool.setGeometry(QRect(100, 430, 161, 41))
        self.equalize_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.negative_bool = QCheckBox(self.general)
        self.negative_bool.setObjectName(u"negative_bool")
        self.negative_bool.setGeometry(QRect(100, 310, 161, 41))
        self.negative_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.log_bool = QCheckBox(self.general)
        self.log_bool.setObjectName(u"log_bool")
        self.log_bool.setGeometry(QRect(100, 370, 161, 41))
        self.log_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.gama_label = QLabel(self.general)
        self.gama_label.setObjectName(u"gama_label")
        self.gama_label.setGeometry(QRect(150, 80, 41, 31))
        self.brightness_label = QLabel(self.general)
        self.brightness_label.setObjectName(u"brightness_label")
        self.brightness_label.setGeometry(QRect(140, 180, 81, 31))
        self.apply_button = QPushButton(self.general)
        self.apply_button.setObjectName(u"apply_button")
        self.apply_button.setGeometry(QRect(100, 700, 131, 31))
        self.apply_button.setStyleSheet(u"background-color: rgb(27, 27, 27);\n"
"color: rgb(255, 255, 255);")
        self.title_general = QLabel(self.general)
        self.title_general.setObjectName(u"title_general")
        self.title_general.setGeometry(QRect(30, 20, 171, 31))
        self.title_general.setLayoutDirection(Qt.LeftToRight)
        self.title_general.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.gama_slider = QSlider(self.general)
        self.gama_slider.setObjectName(u"gama_slider")
        self.gama_slider.setGeometry(QRect(30, 110, 291, 22))
        self.gama_slider.setMinimum(0)
        self.gama_slider.setMaximum(100)
        self.gama_slider.setSliderPosition(100)
        self.gama_slider.setOrientation(Qt.Horizontal)
        self.gama_slider.setInvertedAppearance(False)
        self.brightness_slider = QSlider(self.general)
        self.brightness_slider.setObjectName(u"brightness_slider")
        self.brightness_slider.setGeometry(QRect(30, 220, 291, 22))
        self.brightness_slider.setMinimum(0)
        self.brightness_slider.setMaximum(100)
        self.brightness_slider.setSliderPosition(100)
        self.brightness_slider.setOrientation(Qt.Horizontal)
        self.gama_value_label = QLabel(self.general)
        self.gama_value_label.setObjectName(u"gama_value_label")
        self.gama_value_label.setGeometry(QRect(160, 130, 31, 31))
        self.brightness_value_label = QLabel(self.general)
        self.brightness_value_label.setObjectName(u"brightness_value_label")
        self.brightness_value_label.setGeometry(QRect(160, 240, 31, 31))
        self.histogram_image_widget = QWidget()
        self.histogram_image_widget.setObjectName(u"histogram_image_widget")
        self.histogram_image = QLabel(self.general)
        self.histogram_image.setObjectName(u"histogram_image")
        self.histogram_image.setGeometry(QRect(20, 480, 321, 201))
        self.histogram_image.setMinimumSize(QSize(321, 201))
        Secoes.addWidget(self.general)
        self.filters = QWidget()
        self.filters.setObjectName(u"filters")
        self.title_filters = QLabel(self.filters)
        self.title_filters.setObjectName(u"title_filters")
        self.title_filters.setGeometry(QRect(30, 20, 171, 31))
        self.title_filters.setLayoutDirection(Qt.LeftToRight)
        self.title_filters.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.adjust_box = QGroupBox(self.filters)
        self.adjust_box.setObjectName(u"adjust_box")
        self.adjust_box.setGeometry(QRect(20, 80, 311, 81))
        self.adjust_box.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 700 9pt \"Segoe UI\";")
        self.kernel_size_label = QLabel(self.adjust_box)
        self.kernel_size_label.setObjectName(u"kernel_size_label")
        self.kernel_size_label.setGeometry(QRect(40, 30, 81, 21))
        self.kernel_size_label.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.kernel_size_select = QComboBox(self.adjust_box)
        self.kernel_size_select.addItem("")
        self.kernel_size_select.addItem("")
        self.kernel_size_select.addItem("")
        self.kernel_size_select.addItem("")
        self.kernel_size_select.addItem("")
        self.kernel_size_select.addItem("")
        self.kernel_size_select.setObjectName(u"kernel_size_select")
        self.kernel_size_select.setGeometry(QRect(130, 30, 69, 22))
        self.kernel_size_select.setStyleSheet(u"background-color: rgb(77, 77, 77);")
        self.select_filter_box = QGroupBox(self.filters)
        self.select_filter_box.setObjectName(u"select_filter_box")
        self.select_filter_box.setGeometry(QRect(20, 170, 311, 651))
        self.select_filter_box.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 700 9pt \"Segoe UI\";")
        self.median_bool = QCheckBox(self.select_filter_box)
        self.median_bool.setObjectName(u"median_bool")
        self.median_bool.setGeometry(QRect(40, 50, 161, 41))
        self.median_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.median_simple_w_bool = QCheckBox(self.select_filter_box)
        self.median_simple_w_bool.setObjectName(u"median_simple_w_bool")
        self.median_simple_w_bool.setGeometry(QRect(40, 90, 221, 41))
        self.median_simple_w_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.median_simple_bool = QCheckBox(self.select_filter_box)
        self.median_simple_bool.setObjectName(u"median_simple_bool")
        self.median_simple_bool.setGeometry(QRect(40, 130, 221, 41))
        self.median_simple_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.high_boost_bool = QCheckBox(self.select_filter_box)
        self.high_boost_bool.setObjectName(u"high_boost_bool")
        self.high_boost_bool.setGeometry(QRect(40, 170, 221, 41))
        self.high_boost_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.laplacian_bool = QCheckBox(self.select_filter_box)
        self.laplacian_bool.setObjectName(u"laplacian_bool")
        self.laplacian_bool.setGeometry(QRect(40, 210, 221, 41))
        self.laplacian_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.sobel_x_bool = QCheckBox(self.select_filter_box)
        self.sobel_x_bool.setObjectName(u"sobel_x_bool")
        self.sobel_x_bool.setGeometry(QRect(40, 250, 221, 41))
        self.sobel_x_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.sobel_y_bool = QCheckBox(self.select_filter_box)
        self.sobel_y_bool.setObjectName(u"sobel_y_bool")
        self.sobel_y_bool.setGeometry(QRect(40, 290, 221, 41))
        self.sobel_y_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.nled_bool = QCheckBox(self.select_filter_box)
        self.nled_bool.setObjectName(u"nled_bool")
        self.nled_bool.setGeometry(QRect(40, 330, 221, 41))
        self.nled_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.gray_scale_mean_bool = QCheckBox(self.select_filter_box)
        self.gray_scale_mean_bool.setObjectName(u"gray_scale_mean_bool")
        self.gray_scale_mean_bool.setGeometry(QRect(40, 370, 221, 41))
        self.gray_scale_mean_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.gray_scale_avg_bool = QCheckBox(self.select_filter_box)
        self.gray_scale_avg_bool.setObjectName(u"gray_scale_avg_bool")
        self.gray_scale_avg_bool.setGeometry(QRect(40, 410, 221, 41))
        self.gray_scale_avg_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.low_fourier_bool = QCheckBox(self.select_filter_box)
        self.low_fourier_bool.setObjectName(u"low_fourier_bool")
        self.low_fourier_bool.setGeometry(QRect(40, 450, 221, 41))
        self.low_fourier_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.high_fourier_bool = QCheckBox(self.select_filter_box)
        self.high_fourier_bool.setObjectName(u"high_fourier_bool")
        self.high_fourier_bool.setGeometry(QRect(40, 490, 221, 41))
        self.high_fourier_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.des_fourier_bool = QCheckBox(self.select_filter_box)
        self.des_fourier_bool.setObjectName(u"des_fourier_bool")
        self.des_fourier_bool.setGeometry(QRect(40, 530, 221, 41))
        self.des_fourier_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.limiar_bool = QCheckBox(self.select_filter_box)
        self.limiar_bool.setObjectName(u"limiar_bool")
        self.limiar_bool.setGeometry(QRect(40, 570, 221, 41))
        self.limiar_bool.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        Secoes.addWidget(self.filters)
        self.adjust_box.raise_()
        self.title_filters.raise_()
        self.select_filter_box.raise_()

        self.retranslateUi(Secoes)

        Secoes.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(Secoes)
    # setupUi

    def retranslateUi(self, Secoes):
        Secoes.setWindowTitle(QCoreApplication.translate("Secoes", u"StackedWidget", None))
        self.points_x_values.setPlainText("")
        self.points_y_label.setText(QCoreApplication.translate("Secoes", u"<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Points y</span></p></body></html>", None))
        self.lp_title.setText(QCoreApplication.translate("Secoes", u"<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; color:#ffffff;\">Linear Parts Points</span></p></body></html>", None))
        self.points_x_label.setText(QCoreApplication.translate("Secoes", u"<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Points x</span></p></body></html>", None))
        self.points_y_values.setPlainText("")
        self.see_plot_button.setText(QCoreApplication.translate("Secoes", u"See Plot", None))
        self.lp_bool.setText(QCoreApplication.translate("Secoes", u"Linear Parts Apply", None))
        self.lp_image.setText("")
        self.already_label.setText(QCoreApplication.translate("Secoes", u"<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Already have an encoded image?</span></p></body></html>", None))
        self.esteg_title.setText(QCoreApplication.translate("Secoes", u"<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; color:#ffffff;\">Esteganography</span></p></body></html>", None))
        self.encode_button.setText(QCoreApplication.translate("Secoes", u"Encode", None))
        self.esteg_entry_text.setPlainText("")
        self.decode_button.setText(QCoreApplication.translate("Secoes", u"Decode", None))
        self.decrypted_label.setText(QCoreApplication.translate("Secoes", u"<html><head/><body><p><br/></p></body></html>", None))
        self.equalize_bool.setText(QCoreApplication.translate("Secoes", u"Equalize Histogram", None))
        self.negative_bool.setText(QCoreApplication.translate("Secoes", u"Negative Image", None))
        self.log_bool.setText(QCoreApplication.translate("Secoes", u"Log2", None))
        self.gama_label.setText(QCoreApplication.translate("Secoes", u"<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">Gama</span></p></body></html>", None))
        self.brightness_label.setText(QCoreApplication.translate("Secoes", u"<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">Brightness</span></p></body></html>", None))
        self.apply_button.setText(QCoreApplication.translate("Secoes", u"Apply", None))
        self.title_general.setText(QCoreApplication.translate("Secoes", u"<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; color:#ffffff;\">General</span></p></body></html>", None))
        self.gama_value_label.setText(QCoreApplication.translate("Secoes", u"<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">100</span></p></body></html>", None))
        self.brightness_value_label.setText(QCoreApplication.translate("Secoes", u"<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">100</span></p></body></html>", None))
        self.histogram_image.setText("")
        self.title_filters.setText(QCoreApplication.translate("Secoes", u"<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; color:#ffffff;\">Filters</span></p></body></html>", None))
        self.adjust_box.setTitle(QCoreApplication.translate("Secoes", u"Adjust", None))
        self.kernel_size_label.setText(QCoreApplication.translate("Secoes", u"Kernel Size", None))
        self.kernel_size_select.setItemText(0, QCoreApplication.translate("Secoes", u"3", None))
        self.kernel_size_select.setItemText(1, QCoreApplication.translate("Secoes", u"5", None))
        self.kernel_size_select.setItemText(2, QCoreApplication.translate("Secoes", u"7", None))
        self.kernel_size_select.setItemText(3, QCoreApplication.translate("Secoes", u"9", None))
        self.kernel_size_select.setItemText(4, QCoreApplication.translate("Secoes", u"11", None))
        self.kernel_size_select.setItemText(5, QCoreApplication.translate("Secoes", u"13", None))

        self.select_filter_box.setTitle(QCoreApplication.translate("Secoes", u"Select", None))
        self.median_bool.setText(QCoreApplication.translate("Secoes", u"Median Filter", None))
        self.median_simple_w_bool.setText(QCoreApplication.translate("Secoes", u"Mean Simple Weighted Filter", None))
        self.median_simple_bool.setText(QCoreApplication.translate("Secoes", u"Mean Simple Filter", None))
        self.high_boost_bool.setText(QCoreApplication.translate("Secoes", u"High Boost", None))
        self.laplacian_bool.setText(QCoreApplication.translate("Secoes", u"Laplacian", None))
        self.sobel_x_bool.setText(QCoreApplication.translate("Secoes", u"Sobel X", None))
        self.sobel_y_bool.setText(QCoreApplication.translate("Secoes", u"Sobel Y", None))
        self.nled_bool.setText(QCoreApplication.translate("Secoes", u"Non Linear Edge Detection", None))
        self.gray_scale_mean_bool.setText(QCoreApplication.translate("Secoes", u"Gray Scale Mean", None))
        self.gray_scale_avg_bool.setText(QCoreApplication.translate("Secoes", u"Gray Scale AVG", None))
        self.low_fourier_bool.setText(QCoreApplication.translate("Secoes", u"Low Fourier", None))
        self.high_fourier_bool.setText(QCoreApplication.translate("Secoes", u"High Fourier", None))
        self.des_fourier_bool.setText(QCoreApplication.translate("Secoes", u"Des Fourier", None))
        self.limiar_bool.setText(QCoreApplication.translate("Secoes", u"Limiar", None))
    # retranslateUi

